services:
  db:
    image: 'postgres:15-alpine'
    container_name: db_oauth
    restart: always

    environment:
      - 'POSTGRES_DB=mydb'
      - 'POSTGRES_PASSWORD=12345678'
      - 'POSTGRES_USER=mydb'
    ports:
      - '5432'
    volumes:
      - 'data:/tmp/data'



volumes:
  'data':